### PR TITLE
Update DIDComm RPC with problem report suggestion

### PR DESCRIPTION
**Pull request by amanji**

### CODE REVIEW

**Comment by swcurran** [comment]
I think only the server should send a problem report in response to a `request`.  When the server sends a `response` to the client, it sets the protocol state to `complete` and the protocol is finished from it’s perspective, and the protocol state object can (and should) be deleted. A problem report from the client would be an orphan message at that point since there is no “in-flight” protocol with that threadID.

@amanji, @wadeking98 — while I can see the issue of an invalid `response` message coming from the server, I think only the client controller need know about the failure (via a webhook). The server does not need to be notified.  Presumably, the client or client controller could resend the `request` in hopes of a better answer the next time.

What do you think?

**Comment by amanji** [comment]
One reason why this came up is if the agent message is malformed according to the RFC or the receiver is unable to process it for whatever reason. So it's not so much a user error but an implementation error. This would be picked up with an AIP test suite IMO. Problem Reports may still be useful but, if everything is implemented correctly it wouldn't really ever be an issue.

**Comment by swcurran** [comment]
I’m not saying Problem Reports aren’t useful for the protocol — just that they not be sent when the `response` message is bad, because as soon as that message is sent, the protocol is complete for the server, and as soon as it is received, the protocol is complete for the client.  Sending another message just messes things up.

I do agree that a problem report is a valid response to a `request` message.  Like the `response` message, the problem report message ends the protocol instance.

**Comment by amanji** [comment]
Yeah I agree with the request portion of the protocol for the reasons you outlined above. I can update the wording to reflect that. I'm the case of a response the `requestor` could simply not process the incoming message or complete the interaction and attempt a separate request.

**Comment by amanji** [comment]
I'm still unsure how I feel about having an asymmetric problem report. The Thread ID is sent to indicate which message the report relates to.

**Comment by swcurran** [comment]
> I'm still unsure how I feel about having an asymmetric problem report. The Thread ID is sent to indicate which message the report relates to.

Asymetric as in only on the `request`?

My concern is that when the client sends a problem report after the `request`, the server will have deleted the protocol state object, and the `threadID` will no longer exist (deleted because it is complete) on the server side.  They will have just received an orphan problem report.  What do they do with it?  It’s too late to “fix” the response.

**Comment by amanji** [comment]
Makes sense

**Pull request closed without merging**
